//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelOl4Rent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bien
    {
        public Bien()
        {
            this.Contenidos = new HashSet<Contenido>();
            this.CaracteristicaBien = new HashSet<CaracteristicaBien>();
            this.MeGusta = new HashSet<MeGusta>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public byte[] Foto { get; set; }
        public decimal Latitud { get; set; }
        public decimal Longitud { get; set; }
        public string Direccion { get; set; }
        public string Normas { get; set; }
        public short Capacidad { get; set; }
        public decimal Precio { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaAlquiler { get; set; }
        public short DuracionAlquiler { get; set; }
    
        public virtual ICollection<Contenido> Contenidos { get; set; }
        public virtual ICollection<CaracteristicaBien> CaracteristicaBien { get; set; }
        public virtual TipoBien TipoBien { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<MeGusta> MeGusta { get; set; }
    }
}
