//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelOl4Rent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caracteristica
    {
        public Caracteristica()
        {
            this.CaracteristicaBien = new HashSet<CaracteristicaBien>();
            this.ValorCaracteristicaEspecificacion = new HashSet<ValorCaracteristicaEspecificacion>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public TipoDato Tipo { get; set; }
    
        public virtual TipoBien TipoBien { get; set; }
        public virtual ICollection<CaracteristicaBien> CaracteristicaBien { get; set; }
        public virtual ICollection<ValorCaracteristicaEspecificacion> ValorCaracteristicaEspecificacion { get; set; }
    }
}
