//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelOl4Rent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoBien
    {
        public TipoBien()
        {
            this.Caracteristicas = new HashSet<Caracteristica>();
            this.Bienes = new HashSet<Bien>();
            this.EspecificacionesBien = new HashSet<EspecificacionBien>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
    
        public virtual Sitio Sitio { get; set; }
        public virtual ICollection<Caracteristica> Caracteristicas { get; set; }
        public virtual ICollection<Bien> Bienes { get; set; }
        public virtual ICollection<EspecificacionBien> EspecificacionesBien { get; set; }
    }
}
