//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelOl4Rent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Rol = new HashSet<Rol>();
            this.Sitios = new HashSet<Sitio>();
            this.HabilitacionesUsuarioSitio = new HashSet<HabilitacionUsuarioSitio>();
            this.Bienes = new HashSet<Bien>();
            this.BuzonesMensajes = new HashSet<BuzonMensaje>();
            this.MensajesEnviados = new HashSet<Mensaje>();
            this.WishList = new HashSet<EspecificacionBien>();
            this.BienesMeGusta = new HashSet<MeGusta>();
            this.Contenidos = new HashSet<Contenido>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Mail { get; set; }
        public string NombreUsuario { get; set; }
        public string Contraseña { get; set; }
        public string UsuarioFacebook { get; set; }
        public string UsuarioTwitter { get; set; }
    
        public virtual ICollection<Rol> Rol { get; set; }
        public virtual ICollection<Sitio> Sitios { get; set; }
        public virtual ICollection<HabilitacionUsuarioSitio> HabilitacionesUsuarioSitio { get; set; }
        public virtual ICollection<Bien> Bienes { get; set; }
        public virtual ICollection<BuzonMensaje> BuzonesMensajes { get; set; }
        public virtual ICollection<Mensaje> MensajesEnviados { get; set; }
        public virtual ICollection<EspecificacionBien> WishList { get; set; }
        public virtual ICollection<MeGusta> BienesMeGusta { get; set; }
        public virtual ICollection<Contenido> Contenidos { get; set; }
    }
}
