//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelOl4Rent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValorCaracteristicaEspecificacion
    {
        public int Id { get; set; }
        public string Valor { get; set; }
    
        public virtual EspecificacionBien EspecificacionBien { get; set; }
        public virtual Caracteristica Caracteristica { get; set; }
    }
}
